spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/sample?useSSL=false&allowPublicKeyRetrieval=true
    username: sample_user
    password: sample
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  output:
    ansi:
      enabled: always

server:
  port: 8001

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO
